server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_demo?useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderServer
  cloud:
    nacos:
      server-addr: localhost:8848   #nacos地址
#      discovery:
#        cluster-name: HZ
##        namespace: 751add20-6fd2-4f8c-8559-0467fe348e2f
#        ephemeral: false #是否为临时实例
    sentinel:
      transport:
        dashboard: localhost:8080
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#开启饥饿加载
ribbon:
  eager-load:
    enabled: true   #开启饥饿加载
    clients:        #指定饥饿加载的名称
      - userServer
#负载均衡策略
userServer:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  #负载均衡策略
feign:
  httpclient:
    enabled: true    #支持HttpClient的开关
    max-connections: 200  #最大连接数
    max-connections-per-route: 50  #单个最大连接数

